environments:
  # default wird genommen wenn kein anderes envoronment angegeben wird z.B. (helmfile --environment prod)
  default:
    values:
      - environments/default/values.gotmpl
  # prod: 
  #   values:
  #     - environments/prod/values.yaml

---

repositories:
  - name: 8gears
    url: 8gears.container-registry.com/library
    oci: true
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: ngrok
    url: https://charts.ngrok.com

releases:

  - name: custom-db-bootstrap
    namespace: db-n8n
    createNamespace: true
    chart: charts/custom-db-bootstrap
    values:
      - values/custom-db-bootstrap-values.yaml.gotmpl

  - name: cnpg-operator
    namespace: db-n8n
    chart: cnpg/cloudnative-pg
    version: "0.26.1"
    set:
      - name: config.clusterWide
        value: false
    needs:
      - db-n8n/custom-db-bootstrap
    wait: true

  - name: postgres
    namespace: db-n8n
    chart: cnpg/cluster
    version: "0.3.1"
    values:
      - values/postgresql-values.gotmpl
    needs:
      - db-n8n/cnpg-operator
      - db-n8n/custom-db-bootstrap
    wait: true
  
  - name: ngrok
    namespace: ngrok-operator
    chart: ngrok/ngrok-operator
    version: 0.21.0           
    values:
      - values/ngrok-values.yaml.gotmpl
    wait: true

  - name: custom-n8n
    namespace: n8n
    chart: charts/custom-n8n-chart
    # dieses release erst starten wenn ngrok-operator läuft; sonst können crds nicht gefunden werden
    needs:
      # pattern <namespace>/<release-name>
      - ngrok-operator/ngrok 
      - db-n8n/cnpg-operator
      - db-n8n/postgres
    values:
      - values/custom-n8n-values.yaml.gotmpl

  - name: n8n
    namespace: n8n
    chart: oci://8gears.container-registry.com/library/n8n
    version: 1.1.0
    values:
      - values/n8n-values.yaml.gotmpl
      - global:
          security:
            allowInsecureImages: true

