environments:
  # default wird genommen wenn kein anderes envoronment angegeben wird z.B. (helmfile --environment prod)
  default:
    values:
      - environments/default/values.gotmpl
  # prod: 
  #   values:
  #     - environments/prod/values.yaml

---

repositories:
  - name: 8gears
    url: 8gears.container-registry.com/library
    oci: true
  - name: cloudpirates
    url: registry-1.docker.io/cloudpirates
    oci: true
  - name: ngrok
    url: https://charts.ngrok.com

releases:
  - name: postgres
    namespace: db-n8n
    chart: cloudpirates/postgres
    version: "0.12.0"
    values:
      - values/postgresql-values.gotmpl
    wait: true
  
  - name: ngrok
    namespace: ngrok-operator
    chart: ngrok/ngrok-operator
    version: 0.21.0           
    values:
      - values/ngrok-values.yaml.gotmpl
    wait: true

  - name: custom-n8n
    namespace: n8n
    chart: charts/custom-n8n-chart
    # dieses release erst starten wenn ngrok-operator läuft; sonst können crds nicht gefunden werden
    needs:
      - ngrok-operator/ngrok 
      - db-n8n/postgres
    values:
      - values/custom-n8n-values.yaml.gotmpl
    wait: true

  - name: n8n
    namespace: n8n
    chart: oci://8gears.container-registry.com/library/n8n
    version: 1.1.0
    values:
      - values/n8n-values.yaml.gotmpl
      # nötig um das valkey image zu überschreiben
      - global:
          security:
            allowInsecureImages: true
    needs:
      - n8n/custom-n8n

    

