{{- $ns := .Release.Namespace }}
{{- $n8nService := .Values.agentendpoint.n8nService }}
{{- $webhookService := .Values.agentendpoint.webhookService }}
{{- $endpoints := list
  (dict "name" "n8n-agent"
        "path" $n8nService
        "upstream" (printf "http://n8n.%s.svc.cluster.local:80" $ns))
  (dict "name" 
        "n8n-webhook-agent"
        "path" $webhookService
        "upstream" (printf "http://n8n-webhook.%s.svc.cluster.local:80" $ns))
}}
{{- range $ep := $endpoints }}
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: {{ $ep.name }}
spec:
  url: {{ $ep.path }}
  upstream:
    url: {{ $ep.upstream }}
---
{{- end }}